### ISSUE TITLE
No user-friendly method for sending requests

### ISSUE THREAD

**Issue by smalldev2** [onesoft-sudo/OneHTTP#1]
##### No user-friendly method for sending requests in class `Client`

I think that a method like this:
```php
public function send_request(string $method = "GET", string $url) : bool
{
      // code
}
```
should be added for making it user friendly.

**Comment by virtual-designer** [comment]
We'll add it as soon as possible.
The code will look like this:

```php
public function send_request(string $method = "GET", string $uri, string $host, int $port = 80) : bool
{
      return $this->send_http_query($method, $uri, $host, $port);
}
```
If you have any questions with our code, then feel free to tell us your problem and we'll try our best.
